global:
  resolve_timeout: 1m
  slack_api_url: 'https://2023-winter-bootcamp.slack.com/'

route:
  receiver: 'slack-notifications'

receivers:
- name: 'slack-notifications'
  slack_configs:
    - send_resolved: true